development:
  adapter: sqlite3
  database: db/lunch_ordering_app_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/lunch_ordering_app_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: lunch_ordering_app
  pool: 5
  timeout: 5000